version: "3.9"
services:
  whoami:
    container_name: homelab_whoami
    image: traefik/whoami:latest-arm64
    networks:
      private:
    environment:
      - TZ=America/Sao_Paulo
  cloudflared:
    container_name: homelab_cloudflared
    image: "cloudflare/cloudflared:latest"
    command: "tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN} --protocol quic"
    networks:
      public:
      private:
    environment:
      - TZ=America/Sao_Paulo

networks:
  public:
  private:
    attachable: true
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
          ip_range: 10.1.1.0/24
          gateway: 10.0.0.254