version: "3.9"

networks:
  cloudflared:
    external: true
  private:
    attachable: true
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
          ip_range: 10.1.1.0/24
          gateway: 10.0.0.254

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "10m" 

services:
  whoami:
    container_name: homelab_whoami
    image: traefik/whoami:latest-arm64
    networks:
      private:
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.routers.whoami-rtr.rule=Host(`whoami.andrevandal.dev`)"
      - "traefik.http.routers.whoami-rtr.entrypoints=websecure"
      - "traefik.http.services.whoami-svc.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami-rtr.service=whoami-svc"
      - "traefik.http.routers.whoami.tls.certresolver=cloudflare"
      - "traefik.http.routers.whoami-rtr.middlewares=secure-headers@file,cloudflare-ips@file,real-ip@file"

  cloudflared:
    container_name: homelab_cloudflared
    image: "cloudflare/cloudflared:latest"
    command: "tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN} --protocol quic"
    networks:
      cloudflared:
      private:
    environment:
      - TZ=${TZ}

  traefik:
    <<: *default-opts
    container_name: traefik
    image: "traefik:v2.10.1"
    environment:
      - TZ=${TZ}
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    command:
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=private
      - --log=true
      - --log.level=WARN # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=400-499
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entryPoints.websecure.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
      - --entryPoints.websecure.proxyProtocol.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
      - --experimental.plugins.real-ip.modulename=github.com/Paxxs/traefik-get-real-ip
      - --experimental.plugins.real-ip.version=v1.0.2
      - --providers.file.directory=/rules
      - --providers.file.watch=true
      - --api=true
      - --api.dashboard=true
      - --api.debug=false
      - --metrics.prometheus.addrouterslabels=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/rules:/rules"
      - "./traefik/acme.json:/acme.json"
      - "./traefik/logs/traefik.log:/traefik.log" 
    networks:
      - private
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    restart: unless-stopped